name: ceating-files-workflow

on:
  push:

jobs:
  file-creating-logic:
    runs-on: ubuntu-letest

    steps:
      - name: file-createdd
        run: echo "this file from ci workfolow" > thisCiCdFile.txt


  checking-files:
    needs: file-creating-logic
    runs-on: ubuntu-letest

    steps:
      - name: showingfiles-data
        run: cat thisCiCdFile.txt
